version: '3.4'

services:
  easyword.server.image2word:
    ports:
      - "8001:8000"


  easyword.server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro